server:
  port: 8015   
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: sq-service   
     
management:
  security:
    enabled: false  
 
logging:
  level:
    hpsmservice: DEBUG